import 'package:flutter/material.dart';

import '../l10n/app_localizations.dart'; // generated by gen-l10n (see l10n.yaml)
import 'router.dart';

/// App root: Material 3 + go_router + i18n delegates.
/// No hardcoded title — taken from localization.
class App extends StatelessWidget {
  const App({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp.router(
      onGenerateTitle: (ctx) => AppLocalizations.of(ctx)!.appTitle,
      routerConfig: router,
      localizationsDelegates: AppLocalizations.localizationsDelegates,
      supportedLocales: AppLocalizations.supportedLocales,
      theme: ThemeData(useMaterial3: true),
    );
  }
}
