// Generated by `openapi-typescript` from contracts/api/openapi.yaml.
// Here a hand-written stub so the skeleton runs without a backend.

export interface Example {
  id: string
  label: string
  created_at: string
}

export interface paths {
  "/examples": {
    get: {
      responses: {
        200: { content: { "application/json": { items: Example[] } } }
      }
    }
    post: {
      requestBody: { content: { "application/json": { label: string } } }
      responses: {
        201: { content: { "application/json": Example } }
      }
    }
  }
}
