import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import '../../l10n/app_localizations.dart'; // generated by gen-l10n
import 'example_controller.dart';

/// Example screen of one vertical slice: controller → AsyncValue → UI.
/// No hardcoded text — everything via AppLocalizations (i18n from the first line).
class ExamplePage extends ConsumerWidget {
  const ExamplePage({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final l10n = AppLocalizations.of(context)!;
    final items = ref.watch(exampleControllerProvider);
    return Scaffold(
      appBar: AppBar(title: Text(l10n.exampleTitle)),
      body: items.when(
        loading: () => const Center(child: CircularProgressIndicator()),
        error: (err, _) => Center(child: Text(l10n.exampleError)),
        data: (list) => ListView.builder(
          itemCount: list.length,
          itemBuilder: (_, i) => ListTile(title: Text(list[i].name)),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () => ref.read(exampleControllerProvider.notifier).refresh(),
        tooltip: l10n.exampleRefresh,
        child: const Icon(Icons.refresh),
      ),
    );
  }
}
